pipeline:
  docker:
    image: plugins/docker
    repo: biodranik/docker-dotnet-matlab-2019
    tags: latest
    secrets: [docker_username, docker_password, docker_email]
    when:
      branch: ["master"]
